name: Theme Check

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  theme-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2"

      - name: Install Theme Check
        run: gem install theme-check

      - name: Run Theme Check
        run: theme-check -C .theme-check.yml
